version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: task-management-api-db2
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: task_management_api2
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
